stages:         
  - build
  - test
  - deploy

build-webui:      
    stage: build
    image: docker:latest
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/brahimhamdi/dockercoins-cypress/webui webui/
    - docker push registry.gitlab.com/brahimhamdi/dockercoins-cypress/webui
build-worker:      
    stage: build
    image: docker:latest
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/brahimhamdi/dockercoins-cypress/worker worker/
    - docker push registry.gitlab.com/brahimhamdi/dockercoins-cypress/worker
build-rng:      
    stage: build
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/brahimhamdi/dockercoins-cypress/rng rng/
    - docker push registry.gitlab.com/brahimhamdi/dockercoins-cypress/rng
build-hasher:      
    stage: build
    script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/brahimhamdi/dockercoins-cypress/hasher hasher/
    - docker push registry.gitlab.com/brahimhamdi/dockercoins-cypress/hasher
test-webui:      
    stage: test
    script:
    - docker run -d --rm --name rng -p 8000:80 registry.gitlab.com/brahimhamdi/dockercoins-cypress/webui
    - sleep 20
    - curl http://localhost:8000
    - docker stop rng
test-worker:      
    stage: test
    script:
    - docker run -d --rm --name worker registry.gitlab.com/brahimhamdi/dockercoins-cypress/worker
    - sleep 10
    - docker stop worker
test-rng:      
    stage: test
    script:
    - docker run -d --rm --name rng -p 8001:80 registry.gitlab.com/brahimhamdi/dockercoins-cypress/rng
    - sleep 20
    - curl http://localhost:8001
    - docker stop rng
test-hasher:      
    stage: test
    script:
    - docker run -d --rm --name hasher -p 8002:80 registry.gitlab.com/brahimhamdi/dockercoins-cypress/hasher
    - sleep 20
    - curl http://localhost:8002
    - docker stop hasher
staging:
    stage: deploy
    script:
        - docker-compose down
        - docker-compose up -d
